name = "TensorPACK"
uuid = "31531b1e-8b04-434d-b24f-20dc49cbf098"
authors = ["Thomas E. Baker"]
version = "0.9.5"

[compat]
julia = "1.11.0"
StrassOPen = "0.4.0"
LinearAlgebra = "1.11.0"
Distributed = "1.11.0"
Printf = "1.11.0"
Serialization = "1.11.0"

[deps]
Distributed = "8ba89e20-285c-5b6f-9357-94700520ee1b"
LinearAlgebra = "37e2e46d-f89d-539d-b4ee-838fcccc9c8e"
Printf = "de0858da-6303-5e67-8744-51eddeeeb8d7"
Serialization = "9e88b42a-f829-5b0c-bbe9-9e923198166b"
StrassOPen = "1971c852-c825-11ef-1d57-2185ebdca1d8"
